### ISSUE TITLE
✨ : show outputs at the end of a job

### ISSUE THREAD

**Issue by juwit** [gaia-app/gaia#137]
**Is your feature request related to a problem? Please describe.**
Outputs could be displayed at the end of a job, so users don't have to go back to the "stack" screen to see their outputs.

**Describe the solution you'd like**
Show the output table bellow the "apply" step.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dberuben** [comment]
- Give the option to download it ?

**Comment by juwit** [comment]
Hi @dberuben, and thanks for contributing.
Yeah, downloading outputs could be nice. I'm thinking of a simple JSON file. I've open #187 for this specific feature.
