### ISSUE TITLE
⚡ : JS loading

### ISSUE THREAD

**Issue by juwit** [gaia-app/gaia#192]
**Is your feature request related to a problem? Please describe.**
We have some inline JS on a lot of pages, that require '$' or 'Vue' (we're not on document.onload() callbacks :cry: ).
So I had to put main JS loading in top of pages.
This is an issue as it slows down page loading and rendering.

**Describe the solution you'd like**
Put all JS code in `document.onload` callbacks.

**Describe alternatives you've considered**
Use `window.onload` ?

**Additional context**
N/A

**Comment by cdubuisson** [comment]
see current refactor on #237
