### ISSUE TITLE
➖️ : remove moment-duration-format dependency

### ISSUE THREAD

**Issue by juwit** [gaia-app/gaia#212]
**Is your feature request related to a problem? Please describe.**
`moment-duration-format` dependency is used to format dates at several places in the app.
It would be better to use a standard solution such as `Intl.DateTimeFormat`

**Describe the solution you'd like**
Use `Intl.DateTimeFormat`.
Here is an example of replacement of `moment().format('LLL');` does:
```
const options = {
  "month" : "long",
  "day" : "numeric",
  "year": "numeric",
  "hour": "numeric",
  "minute": "numeric"
};

console.log(new Intl.DateTimeFormat('fr-FR', options).format(new Date()));
console.log(new Intl.DateTimeFormat('en-US',options).format(new Date()));

> "23 janvier 2020 à 14:45"
> "January 23, 2020, 2:45 PM"
```

**Describe alternatives you've considered**
Keep the dependency.

**Additional context**
Link to the doc: 
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DateTimeFormat

Browser compatibility : 
![image](https://user-images.githubusercontent.com/7531844/72989786-3db56e80-3def-11ea-9845-508739d21f8e.png)

**Comment by cdubuisson** [comment]
moment-duration-format was used only for duration display between two dates in vue component `job-timer`.
I rewrote the component to use vanilly instead.
I take the opportunity to remove moment dependency as well to use vanilla the way you advise.

see https://github.com/gaia-app/gaia/pull/215
