### ISSUE TITLE
✨ : Integration with Hashicorp Vault for secrets and securely storing state files

### ISSUE THREAD

**Issue by binlab** [gaia-app/gaia#236]
**Is your feature request related to a problem? Please describe.**
Thanks for the nice work!
It would be nice to add integration with `Hashicorp Vault` for storing and obtaining secrets as an `environment` or `values`. And also would be great to use Vault Transit `encryption/decryption` for securely storing state files (possibly some leak of sensitive information via the state file). Can you investigate this?

**Describe the solution you'd like**
`Hashicorp Vault` Secret backend and Transit backend

**Describe alternatives you've considered**
It can by other solution, but `Hashicorp Vault` has native integration with Terraform

**Additional context**
- https://learn.hashicorp.com/vault/getting-started/secrets-engines
- https://learn.hashicorp.com/vault/encryption-as-a-service/eaas-transit

**Comment by juwit** [comment]
Hi @binlab !
Thank you for contributing with this issue !
Yes, we plan to develop an integration with a secret manager (Vault is great) as well as some configuration screens to input them securely, and share them across modules and teams.
We didn't thought of securing state files, but it sounds like a great idea !

As for now, we're working on re-writing our front-end, and will develop more features as soon as it is finished. Maybe we'll also publish a roadmap somewhere, to give some visibility about the upcoming features !
Stay tuned !

**Comment by binlab** [comment]
Thank you!
