### ISSUE TITLE
✨ : Import Service Account JSON variable

### ISSUE THREAD

**Issue by judika03** [gaia-app/gaia#286]
Is your feature request related to a problem? Please describe.
How to import Service Account JSON GCP file to runner ? 
`provider "google" {
  credentials = file location
  project     = "tesringt"
  region      = "australia-southeast1"
}`
GAIA have provide enviroment variabel to expoort CREDENTIAL, but location file json from local to inside container terraform, not found.

How to bind service account json to container terraform via /var/run/docker.sock?

Describe the solution you'd like
Provide variable to attach service account to access resource to cloud.

**Comment by juwit** [comment]
Hello,

Thank you for contributing by opening this issue.
As for now, there's no credentials management in Gaia.
It's a feature we're planning to do in the future.

There's some steps you can try :

As the Terraform GCP provider documentation says :
https://www.terraform.io/docs/providers/google/guides/provider_reference.html#credentials

Credentials can be the path or the contents of a service account key file, in JSON.

Maybe you can try to create a terraform variable for the service account, and use it in the `provider` block?
Then in Gaia, you should be able to fill the variable with your service account JSON.

Hope it helps.

Regards

**Comment by juwit** [comment]
Hello,

Thank you for contributing by opening this issue.
As for now, there's no credentials management in Gaia.
It's a feature we're planning to do in the future.

There's some steps you can try :

As the Terraform GCP provider documentation says :
https://www.terraform.io/docs/providers/google/guides/provider_reference.html#credentials

Credentials can be the path or the contents of a service account key file, in JSON.

Maybe you can try to create a terraform variable for the service account, and use it in the `provider` block?
Then in Gaia, you should be able to fill the variable with your service account JSON.

Hope it helps.

Regards

**Comment by judika03** [comment]
but I'm already to use enviroment variable to service account json, but it have problem path service account JSON(Not found), What suggest path enviroment variabel in Gaia to runner docker?
