### ISSUE TITLE
✨ : issue Terraform 0.13 compatibility

### ISSUE THREAD

**Issue by ArieHein** [gaia-app/gaia#390]
Specifically looking for the module source as a requirement if not from TF registry and Module dependencies.

**Comment by juwit** [comment]
Hello @ArieHein ! Thank you for opening this issue !

As we use the official terraform docker image to run our modules, we are already be compatible with terraform 0.13.
Modules sources from TF registry, S3, GCP Buckets, Git and HTTP Urls should work.
Modules sources from local path will not.

Some other features may not work as expected, as we need to adapt some stuff and test with 0.13
The custom validation rules feature of 0.13 may break the variable detection when importing modules.

We plan to make Gaia a full compatible terraform registry in the future. So Gaia could become a module source itself !

**Comment by ArieHein** [comment]
Appreciate the quick answer ! Thanks !!
