### ISSUE TITLE
✨ : Better user management

### ISSUE THREAD

**Issue by hongkongkiwi** [gaia-app/gaia#450]
Hi, I would like to be able to set the initial admin password via a ENV variable. If a user already exists in the db, then it should ignore this.

I would like to be able to create new users via the admin user and change their details (e.g. password).

I would also like to be able to change my own user password, rather than having it hard coded.

**Comment by juwit** [comment]
Hi @hongkongkiwi and thank you for contributing by opening this issue !

The `admin` password can be changed using the environment variable "GAIA_ADMINPASSWORD".
The `user` password cannot be changed. We may delete this user in the future as it is mainly intended for tests.

As for now, hard-coded users are not stored in the database, and it is not possible to create new users.

We'll add this in our backlog :)
