### ISSUE TITLE
✨ : delete stacks

### ISSUE THREAD

**Issue by juwit** [gaia-app/gaia#529]
**Is your feature request related to a problem? Please describe.**
When a stack is archived, we may also want to delete it.

**Describe the solution you'd like**
If we want to `delete` stacks : 
* delete them from the collections
* also delete jobs, states, and so on

**Describe alternatives you've considered**
N/A

**Additional context**
A Stack should only be deleted by its owner, or a admin user.

**Comment by 5er9e1** [comment]
I also want to ask about `Modules`. Is it deletable? I couldn't find way how to remove it.

**Comment by juwit** [comment]
I've open another issue for modules deletion : #724
