### ISSUE TITLE
Runner Issue

### ISSUE THREAD

**Issue by dasari97** [gaia-app/gaia#702]
I created docker-compose.yml file and using docker compose commad , i build gaia and runner in my amazon linux VM.

The runner is not able to connect with gaia. 

https://github.com/dasari97/betsol-test.git

please check the log-file and docker-compose.yml file in the above mentioned repo and help me out with the issue.

**Comment by dasari97** [comment]
issue resolved.

**Comment by jbrardport** [comment]
@dasari97 How did you resolve?

**Comment by dasari97** [comment]
Hey jbrardport,


I was just copy pasting the compose file content, but I tried to provide the private  ip's in place localhost and then it started working.

**Comment by dasari97** [comment]
@jbrardport
