### ISSUE TITLE
🐛 : PLAN Failed: Runner execution with result code 7.

### ISSUE THREAD

**Issue by jbrardport** [gaia-app/gaia#711]
**Describe the bug**
I am running locally using the docker-compose.
I have a simple terraform module to run.
I am getting Plan Failed everytime.

**To Reproduce**
```yml
version: "3.9"
services:
  gaia:
    image: "gaiaapp/gaia"
    expose:
      - 8080
    ports: 
      - "8080:8080"
    environment:
      - "GAIA_MONGODB_URI=mongodb://mongo/gaia"
      - "GAIA_RUNNER_API_PASSWORD=123456"
      - "GAIA_EXTERNAL_URL=http://127.0.0.1:8080"
  runner:
    image: "gaiaapp/runner"
    environment:
      - "GAIA_URL=http://gaia:8080"
      - "GAIA_RUNNER_API_USERNAME=gaia-runner"
      - "GAIA_RUNNER_API_PASSWORD=123456"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
  mongo:
    image: "mongo:4.4"
```

You can view my module from github here:
https://github.com/jbrardport/terraform-modules

It's a simple `null_resource`

**Expected behavior**
I would expect the plan to complete successfully.

**Screenshots**
Plan error:
```sh
[gaia] using image hashicorp/terraform:latest
[gaia] installing curl
[gaia] cloning https://oauth2:[MASKED]@github.com/jbrardport/terraform-modules
Cloning into 'module'...
[gaia] generating backend configuration
[gaia] generating tfvars variable file
```
In this output I'm using github oauth2, but the same error occurs when just manually importing.

Runner Logs:
```sh
2022-05-20 18:47:40.047  INFO 1 --- [   scheduling-1] io.gaia_app.runner.StepPoller            : Polling for pending steps

2022-05-20 18:47:40.306  INFO 1 --- [   scheduling-1] io.gaia_app.runner.StepPoller            : Step found 72a35f0e-56ce-4704-b992-e725d43dce18. Running.

2022-05-20 18:47:40.524  INFO 1 --- [  gaia-runner-1] io.gaia_app.runner.StepRunner            : Starting step 72a35f0e-56ce-4704-b992-e725d43dce18 execution.

2022-05-20 18:47:44.462  INFO 1 --- [  gaia-runner-1] io.gaia_app.runner.StepRunner            : Finished step 72a35f0e-56ce-4704-b992-e725d43dce18 execution with result code 7.
```

**Desktop (please complete the following information):**
 - macOS
 - Chrome

**Additional context**

**Comment by juwit** [comment]
Hi @jbrardport and thank you for the detailed issue.
I believe you got the error because the property `GAIA_EXTERNAL_URL` is `127.0.0.1:8080`

To explain:
* this property is used by Gaia to generate the script to be run in the Terraform containers.
* when running in the terraform container, `127.0.0.1` redirects to the container itself, hence the error at the *generating tfvars phase*

To solve this, you can try to use this values for `GAIA_EXTERNAL_URL`:
* the real IP of your machine, eg `192.168.1.12:8080`
* the IP of your machine in the docker bridge network, defaults to `172.17.0.1:8080`

**Comment by jbrardport** [comment]
Hello @juwit 

So I ran the following commands (outputs shortened):
```sh
$ docker network list
...
NETWORK ID     NAME           DRIVER    SCOPE
...
e4677189d853   test_default   bridge    local
...
```
```sh
$ docker network inspect test_default
[
    {
        "Name": "test_default",
        ...
        "IPAM": {
            ...
            "Config": [
                {
                    "Subnet": "172.20.0.0/16",
                    "Gateway": "172.20.0.1"
                }
            ]
...
```

I have updated the `docker-compose.yml` to have `GAIA_EXTERNAL_URL=172.20.0.1:8080` and the plan has progressed further than before.

I am now seeing a terraform docker container spun up.

Problem is, I'm now seeing exit code 28 in the runner.

Runner logs as followed:

```sh
test-runner-1  | 2022-05-21 18:02:10.172  INFO 1 --- [  gaia-runner-1] io.gaia_app.runner.StepRunner            : Finished step a70f7d65-43ea-4a76-956b-2df4f44c0d63 execution with result code 28.
test-runner-1  | 2022-05-21 18:02:10.173  INFO 1 --- [  gaia-runner-1] io.gaia_app.runner.StepRunner            : Sending result.
```

Looks like it is some kind of timeout?
Let me know, I appreciate your help.

**Comment by jbrardport** [comment]
UPDATE:

So I tried using [colima](https://github.com/abiosoft/colima) instead of normal Docker Desktop and the plan was created successfully! 

I will keep this issue a little longer to see if anyone has information to add to my previous comment.

**Comment by jbrardport** [comment]
Closing this
